### ISSUE TITLE
Image files don't open

### ISSUE THREAD

**Issue by david-tejada** [paul-schaaf/talon-filetree#14]
For example here, saying `tree harp` doesn't open the image:
<img width="245" alt="Screenshot 2023-05-15 at 14 43 35" src="https://github.com/paul-schaaf/talon-filetree/assets/3219671/5c037a53-9031-463a-93f5-c2cddbc67cf9">

I think instead of this
```typescript
await vscode.window.showTextDocument(uri);
```
we should use this
```typescript
await vscode.commands.executeCommand("vscode.open", uri);
```

I can include this in #13 if you want.

**Comment by paul-schaaf** [comment]
closed by #13
