### ISSUE TITLE
request: "tree scout <user.letters>" to "Find in Folder..."

### ISSUE THREAD

**Issue by ghouston** [paul-schaaf/talon-filetree#15]
"tree scout <user.letters>" which would do the same as "Find in Folder..." in the File Explorer sidebar.

If the user.letters refer to file instead of a folder, maybe it would search the file's parent folder.

**Comment by paul-schaaf** [comment]
I think this requires a change to VSCode as I dont think this functionality is currently exposed through the API. I created an issue https://github.com/microsoft/vscode/issues/204922

**Comment by david-tejada** [comment]
We don't need any additional vscode API to achieve this. I just implemented it and it's working fine. I will make a couple of PR to add this functionality.

**Comment by paul-schaaf** [comment]
sweet!
