### ISSUE TITLE
filetree extension does not support multi-root folder vscode workspaces

### ISSUE THREAD

**Issue by saidelike** [paul-schaaf/talon-filetree#16]
If there are more than 1 "root" folder in the vscode workspace, the tree bar only shows the content of the first "root" folder (i.e. files and folder in that first "root" folder, it does not even show the "root" folder itself). 

Consequently, it does not show a second "root" folder if it is there. So we can't use the file tree for other "root" folders if there are more than one.

**Comment by paul-schaaf** [comment]
thanks @pokey looks like I can!

**Comment by pokey** [comment]
You also might check out the setup we have [on cursorless-talon](https://github.com/cursorless-dev/cursorless-talon/issues), where we have a pinned issue telling people to file issues against the main repo

**Comment by paul-schaaf** [comment]
much obliged @pokey !

**Comment by saidelike** [comment]
It is solved so closing
